name: Node.js CI

on: [push]

jobs:
  lint_and_test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
      - run: npm ci --omit dev
      - run: npm run lint
      - run: npm test
